version: '3' 

services:
  book-service:
    build: .vnjnjkn
    volumes:
      - ./book.py:/book.py
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
